export const resumeContent = {
  headline:
    'Technical Product Owner | Software Engineer | Digital & Operational Systems',
  summary: [
    'Technical Product Owner and Software Engineer with experience across technical operations, real-time systems, data collection and validation, software testing, troubleshooting, and process improvement. Hands-on background building and improving software systems, analyzing operational and performance data, reproducing and documenting issues, defining validation criteria, and improving reliability based on observed behavior.',
    'Experienced partnering with engineering and QA teams to investigate failures, validate changes, and support technically complex operational workflows. Brings extensive hands-on motorsports experience and familiarity with vehicle setup, track environments, simulator systems, telemetry, and performance data.',
  ],
  strengths: [
    {
      label: 'Programming & systems',
      items: [
        'Python',
        'TypeScript',
        'JavaScript',
        '.NET',
        'Node.js / Express',
        'React',
        'REST APIs',
        'Distributed systems',
        'Real-time systems',
      ],
    },
    {
      label: 'Testing & troubleshooting',
      items: [
        'Software testing',
        'Defect triage',
        'Issue reproduction',
        'Root cause analysis',
        'UAT',
        'Acceptance criteria validation',
        'Playwright',
        'Vitest',
        'Production support',
      ],
    },
    {
      label: 'Data & analysis',
      items: [
        'SQL',
        'PostgreSQL',
        'MongoDB',
        'Data collection',
        'Data validation',
        'Data quality',
        'Operational metrics',
        'Reporting',
        'Behavioral data',
        'Data workflows',
      ],
    },
    {
      label: 'Product & engineering',
      items: [
        'Technical requirements',
        'User stories',
        'Acceptance criteria',
        'PRDs',
        'Backlog management',
        'Release validation',
        'Cross-functional engineering collaboration',
        'Agile / Scrum',
        'Jira',
        'Linear',
      ],
    },
    {
      label: 'AI & automation',
      items: [
        'LLM API integration',
        'RAG',
        'Agentic workflows',
        'Vector databases',
        'Embeddings',
        'LangChain',
        'MCP',
      ],
    },
    {
      label: 'Motorsports & simulation',
      items: [
        'iRacing SDK',
        'Simulator systems',
        'Telemetry',
        'Performance data',
        'Vehicle setup',
        'Suspension setup',
        'Track environments',
      ],
    },
    {
      label: 'Other',
      items: ['Tailwind CSS', 'shadcn/ui', 'Figma', 'Unity'],
    },
  ],
  experience: [
    {
      company: 'CTX Motoworks',
      role: 'Assistant General Manager (Part-time, Operations & E-commerce)',
      dates: 'Jul 2025 - May 2026',
      bullets: [
        'Owned and improved service, inventory, customer communication, repair tracking, billing, and operational workflows in a high-volume motorcycle dealership environment.',
        'Monitored repair status, vehicle readiness, queue age, service capacity, and operational bottlenecks to identify issues requiring investigation or corrective action.',
        'Analyzed service capacity, aging work, revenue trends, and throughput to prioritize workflow and staffing changes, contributing to a $90,000 service revenue increase in one month.',
        'Investigated recurring service and workflow problems, documented findings, and coordinated resolution across technicians, service advisors, parts staff, and management.',
        'Gathered feedback across sales, service, parts, customers, and leadership to identify workflow failures, clarify ownership, and define process improvements.',
        'Defined product direction and requirements for an internal dealership platform connecting customer messaging, service workflows, payments, inventory, task ownership, and management reporting. That platform became Attend, listed under selected products below.',
      ],
    },
    {
      company: 'Lambda Curry',
      role: 'Product Owner (Contract, Full-time)',
      dates: 'May 2025 - Feb 2026',
      bullets: [
        'Guided multiple software products across consumer, e-commerce, B2B, and healthcare domains through requirements definition, development, testing, release, and iteration.',
        'Partnered with engineering and QA to reproduce issues, compare expected and actual behavior, identify edge cases, assess impact, and validate completed changes.',
        'Triaged defects by confirming reproduction conditions, documenting observed behavior, assessing severity and business impact, and coordinating resolution.',
        'Translated business goals, user behavior, product data, and stakeholder feedback into technical requirements, user stories, acceptance criteria, and prioritized work.',
        'Wrote PRDs for higher-risk features documenting workflows, dependencies, failure conditions, edge cases, validation criteria, and success metrics.',
        'Defined requirements and success criteria for a checkout redesign that contributed to a 12 percent first-week sales lift.',
        'Used behavioral data, conversion trends, and retention patterns to prioritize fixes and product improvements, driving 10-25 percent retention improvement across a multi-product platform.',
      ],
    },
    {
      company: 'Humane Society of New Braunfels (HSNBA)',
      role: 'Software Engineer (Volunteer, Full-stack & SQL Automation)',
      dates: 'Apr 2024 - Present',
      bullets: [
        'Built Python and SQL tools for collecting, cleaning, validating, and processing operational data, reducing manual data entry by 65 percent and data errors by 95 percent.',
        'Built repeatable workflows to process and classify more than 19,000 animal-control records for reporting, geospatial analysis, grant planning, and operational decision-making.',
        'Developed validation logic to identify missing, inconsistent, duplicate, and incorrectly classified records before downstream analysis.',
        'Integrated external GIS datasets and APIs into internal systems to automate classification and reporting.',
        'Investigated data-quality issues and documented transformation rules, validation logic, and system behavior to improve reliability, auditability, and maintainability.',
      ],
    },
  ],
  selectedProjects: ['Oasis Race Control', 'Track Tuner', 'Attend', 'RideSense'],
  activeBuilds: [
    'Oasis Race Control: real-time sim-racing operations platform connecting 20+ simulator stations, driver sessions, iRacing SDK timing and telemetry, front-of-store displays, and venue staff, with defined behavior for simulator disconnects, application restarts, interrupted delivery, and recovery.',
    'Track Tuner: motorsports data platform for recording vehicle setup, track conditions, rider observations, and session performance, with structured comparison between setup changes and observed vehicle behavior and a retrieval-based analysis grounded in the rider’s own session history.',
    'Attend: shared dealership operations platform for service teams managing customer communication, follow-up work, service updates, tasks, and parts notifications, with AI-assisted briefs that summarize conversations and rank the queue by what they flag.',
    'RideSense: cross-provider cycling training insights platform with similarity-scored deduplication, canonical activity modeling, deterministic weekly load and zone analytics, and evidence-backed AI responses.',
  ],
  credentials: [
    'University of Colorado Boulder - M.S. Computer Science (in progress)',
    'Texas State University - B.S. Advertising',
    'Harvard CS50',
  ],
};
